name: minimal_flutter_missing_classes
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2
  google_sign_in_android: ^6.1.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true